import {
  BookOpen,
  Brain,
  Calendar,
  Camera,
  CheckCircle,
  Circle,
  Clock,
  Code,
  Coffee,
  Dumbbell,
  FileText,
  Flag,
  Hammer,
  Image as ImageIcon,
  Lightbulb,
  ListChecks,
  Mail,
  MessageSquare,
  Mic,
  Music,
  Pencil,
  PenLine,
  Phone,
  Rocket,
  Search,
  Star,
  Target,
  TrendingUp,
  Users,
  Video,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';
import type { CompassMissionIcon } from 'samwell-shared';

/** Maps the icon name Samwell picked (constrained to COMPASS_MISSION_ICONS) to one of our icons. */
const MISSION_ICONS: Record<CompassMissionIcon, LucideIcon> = {
  video: Video,
  mic: Mic,
  camera: Camera,
  wrench: Wrench,
  hammer: Hammer,
  target: Target,
  'book-open': BookOpen,
  pencil: Pencil,
  pen: PenLine,
  search: Search,
  code: Code,
  dumbbell: Dumbbell,
  brain: Brain,
  lightbulb: Lightbulb,
  clock: Clock,
  'check-circle': CheckCircle,
  flag: Flag,
  zap: Zap,
  'list-checks': ListChecks,
  'message-square': MessageSquare,
  mail: Mail,
  phone: Phone,
  'file-text': FileText,
  image: ImageIcon,
  music: Music,
  'trending-up': TrendingUp,
  coffee: Coffee,
  users: Users,
  calendar: Calendar,
  rocket: Rocket,
  star: Star,
  circle: Circle,
};

export function missionIcon(name: string): LucideIcon {
  return MISSION_ICONS[name as CompassMissionIcon] ?? Circle;
}
